// Wraps the OpenNext worker with Cron + Queue handlers for bot scheduling.
// Built after `opennextjs-cloudflare build`; wrangler `main` points here.
// @ts-expect-error — generated by OpenNext build
import openNextWorker from "./.open-next/worker.js";

type FetchHandler = (
  request: Request,
  env: CloudflareEnv,
  ctx: ExecutionContext,
) => Response | Promise<Response>;

interface OpenNextExport {
  fetch: FetchHandler;
}

const base = (openNextWorker as { default?: OpenNextExport }).default ?? (openNextWorker as OpenNextExport);

async function invokeInternal(
  path: string,
  env: CloudflareEnv,
  body?: { botId: string },
): Promise<Response> {
  const secret = env.CRON_SECRET;
  if (!secret) {
    throw new Error("CRON_SECRET is not configured");
  }
  const service = env.WORKER_SELF_REFERENCE;
  if (!service) {
    throw new Error("WORKER_SELF_REFERENCE is not configured");
  }

  return service.fetch(`https://polyagent-internal${path}`, {
    method: "POST",
    headers: {
      "x-cron-secret": secret,
      ...(body ? { "content-type": "application/json" } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
  });
}

export default {
  fetch: base.fetch.bind(base),

  async scheduled(_controller: ScheduledController, env: CloudflareEnv, ctx: ExecutionContext) {
    ctx.waitUntil(invokeInternal("/api/internal/cron", env));
  },

  async queue(batch: MessageBatch<{ botId?: string }>, env: CloudflareEnv, ctx: ExecutionContext) {
    for (const message of batch.messages) {
      const botId = message.body?.botId;
      if (botId) {
        ctx.waitUntil(
          invokeInternal("/api/internal/queue", env, { botId }).then(() => message.ack()),
        );
      } else {
        message.ack();
      }
    }
  },
};